In [4]:
#import libraries
import pandas as pd
import numpy as np

In [5]:
#import database 
df=pd.read_csv("Emp_data.csv")
df.head()

,employee_id,employee_name,email,department,designation,location,gender,age,marital_status,education,...,bonus_lpa,performance_rating,last_appraisal_percent,satisfaction_score,attrition_status,attrition_reason,projects_handled,overtime_hours_monthly,work_from_home_days,leaves_taken
0,1001,Amit Sharma,amit.sharma1001@srijanrealty.com,Sales,Sales Intern,Kolkata,Male,22,Single,B.Com,...,0.25,3.2,11,2.5,Left,Better Opportunity,2.0,5.0,0.0,4.0
1,1002,Priya Das,priya.das1002@srijanrealty.com,Marketing,Digital Marketing Exec,New Town,Female,23,Single,B.Tech,...,0.65,3.3,11,2.6,Active,NaN,3.0,8.0,1.0,5.0
2,1003,Rahul Kumar,rahul.kumar1003@srijanrealty.com,Construction,Civil Engineer,Rajarhat,Male,24,Single,M.Tech,...,1.20,3.4,11,2.7,Active,NaN,4.0,11.0,2.0,6.0
3,1004,Sneha Ghosh,sneha.ghosh1004@srijanrealty.com,HR,HR Manager,Asansol,Female,25,Single,MBA,...,1.45,3.5,12,2.8,Left,Relocation,5.0,14.0,3.0,7.0
4,1005,Vikash Banerjee,vikash.banerjee1005@srijanrealty.com,Finance,CFO,Behala,Male,26,Single,BBA,...,1.80,3.6,12,2.9,Active,NaN,6.0,17.0,4.0,8.0

In [6]:
# 1.check info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10140 entries, 0 to 10139
Data columns (total 25 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   employee_id             10140 non-null  int64
 1   employee_name           10140 non-null  object
 2   email                   10140 non-null  object
 3   department              10140 non-null  object
 4   designation             10140 non-null  object
 5   location                10140 non-null  object
 6   gender                  10140 non-null  object
 7   age                     10140 non-null  int64
 8   marital_status          10140 non-null  object
 9   education               10140 non-null  object
 10  joining_date            10140 non-null  object
 11  experience_years        10140 non-null  int64
 12  total_experience        10140 non-null  int64
 13  previous_company        10140 non-null  object
 14  salary_lpa              10140 non-null  float64
 15  bonus_lpa               10140 non-null  float64
 16  performance_rating      10140 non-null  float64
 17  last_appraisal_percent  10140 non-null  int64
 18  satisfaction_score      10140 non-null  float64
 19  attrition_status        10139 non-null  object
 20  attrition_reason        10018 non-null  object
 21  projects_handled        10139 non-null  float64
 22  overtime_hours_monthly  10139 non-null  float64
 23  work_from_home_days     10139 non-null  float64
 24  leaves_taken            10139 non-null  float64
dtypes: float64(8), int64(5), object(12)
memory usage: 1.9+ MB

In [7]:
#2. Department wise count
df['department'].value_counts()

department
Finance             1220
HR                  1155
Customer Service    1152
Marketing           1147
Sales               1144
Construction        1111
Legal               1103
IT                  1069
Operations          1039
Name: count, dtype: int64

In [8]:
#3. attrition_status count
df['attrition_status'].value_counts()

attrition_status
Active    8636
Left      1503
Name: count, dtype: int64

In [9]:
#4. Average salary by department
df.groupby('department')['salary_lpa'].agg(['mean','min','max','count']).round(2)

                   mean  min   max  count
department
Construction      10.78  2.5  23.0   1111
Customer Service  10.79  2.5  23.0   1152
Finance           11.01  2.5  23.0   1220
HR                10.68  2.5  23.0   1155
IT                10.69  2.5  23.0   1069
Legal             10.75  2.5  23.0   1103
Marketing         10.84  2.5  23.0   1147
Operations        10.68  2.5  23.0   1039
Sales             10.96  2.5  23.0   1144

In [10]:
#5. create new column= "exact_salary"
df['exact_salary']=(df['salary_lpa']*100000).astype(int)
#6. create a new column name of "monthly salary"
df['monthly_salary']=(df['exact_salary']/12).astype(int).round(2)
df[['employee_name','department','total_experience','age','monthly_salary']].head(10)

     employee_name        department  total_experience  age  monthly_salary
0      Amit Sharma             Sales                 9   22           20833
1        Priya Das         Marketing                 9   23           54166
2      Rahul Kumar      Construction                 9   24          100000
3      Sneha Ghosh                HR                 9   25          120833
4  Vikash Banerjee           Finance                 9   26          150000
5     Anjali Patel                IT                 3   27           37500
6    Sourav Tiwari  Customer Service                 3   28           87500
7       Neha Yadav             Legal                 3   29           62500
8   Rohan Malhotra        Operations                11   30           79166
9      Pooja Verma             Sales                11   31          141666

In [11]:
#filling null values
# For attrition status fill with not active
df['attrtion_status']=df['attrition_status'].fillna('Not Active')
df['attrtion_status']

0          Left
1        Active
2        Active
3          Left
4        Active
          ...
10135    Active
10136    Active
10137    Active
10138    Active
10139      Left
Name: attrtion_status, Length: 10140, dtype: object

In [12]:
#filling null values
# for numeric columns
df['projects_handled']=df['projects_handled'].fillna(df['projects_handled']).median()
df['projects_handled']

0        16.0
1        16.0
2        16.0
3        16.0
4        16.0
         ...
10135    16.0
10136    16.0
10137    16.0
10138    16.0
10139    16.0
Name: projects_handled, Length: 10140, dtype: float64

In [13]:
#filling the null values with NA
df['attrition_reason']=df['attrition_reason'].fillna('N/A - Active')
df['attrition_reason']

0        Better Opportunity
1              N/A - Active
2              N/A - Active
3                Relocation
4              N/A - Active
                ...
10135            Relocation
10136         Work Pressure
10137         Work Pressure
10138            Low Salary
10139            Low Salary
Name: attrition_reason, Length: 10140, dtype: object

In [23]:
# Education wise employee count
df.groupby('education')['education'].value_counts().sort_values()

education
LLB              819
MCA              855
M.Com            889
B.Tech           907
Diploma Civil    915
BCA              945
B.Arch           950
B.Com            950
BBA              954
M.Tech           971
MBA              985
Name: count, dtype: int64

In [27]:
# Maratial status wise employee count
df.groupby('marital_status')['department'].value_counts()

marital_status  department
Married         Customer Service    436
                Sales               420
                Finance             413
                Construction        388
                Marketing           385
                HR                  384
                IT                  375
                Legal               371
                Operations          364
Single          Finance             807
                HR                  771
                Marketing           762
                Legal               732
                Sales               724
                Construction        723
                Customer Service    716
                IT                  694
                Operations          675
Name: count, dtype: int64

In [41]:
# Department wise average monthly salary
df.groupby('department')['monthly_salary'].mean().round(0).sort_values()

department
Operations          88995.0
HR                  89026.0
IT                  89086.0
Legal               89570.0
Construction        89836.0
Customer Service    89941.0
Marketing           90319.0
Sales               91298.0
Finance             91748.0
Name: monthly_salary, dtype: float64

In [42]:
# Saving the file
df.to_csv("srijan_emp.csv",index = False)
print("File Saved!")

File Saved!